[workspace]
members = [
    "validator-collective",
    "metamui-primitives",
    "node-authorization",
    "node-authorities",
    "validator-set",
    "collective",
    "balances",
    "did",
    "token",
    "vc"
]
[profile.release]
panic = "unwind"
