[workspace]
members = [
    "validator-collective",
    "metamui-primitives",
    "node-authorization",
    "node-authorities",
    "validator-set",
    "collective",
    "balances",
    "did",
    "check-access",
    "token",
    "vc",
    "collator-selection"
]
[profile.release]
panic = "unwind"
