[workspace]
members = [
    "metamui-primitives",
    "node-authorities",
    "node-authorization",
    "validator-set",
    "collective",
    "balances",
    "did"
]
[profile.release]
panic = "unwind"
